using System;
using System.Collections.Generic;
using System.Text;

namespace TextImageEncryptor
{
    public static class Statics
    {
        public static string text =
               @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id fringilla nulla. Donec vitae lorem at nisi sagittis maximus. Proin gravida consectetur lacinia. Nulla condimentum tellus non cursus scelerisque. Proin accumsan dui sit amet laoreet volutpat. Etiam nec porttitor enim. Nullam libero libero, facilisis at enim at, tempus dignissim dui. Sed tincidunt cursus tortor, vel sollicitudin ipsum porttitor eu. Phasellus ultrices ultricies nunc, at tincidunt lorem vulputate eget. Pellentesque molestie tempus aliquet. Nullam elementum felis ante, at malesuada metus tristique sed. Proin ut est at turpis euismod pretium sed eu sem. Curabitur congue neque hendrerit arcu tincidunt vulputate. Proin lacus urna, lobortis a leo id, commodo suscipit ligula.

Nunc ut rutrum dui. Maecenas elementum faucibus cursus. Fusce tellus nisl, vestibulum sed tempus vitae, aliquam ac felis. Donec faucibus magna sapien, in porta ipsum elementum vitae. Duis eros ante, molestie in dolor nec, ultrices sodales sem. Ut fermentum nunc et luctus egestas. Etiam vitae metus dolor. Sed fermentum, leo quis efficitur tempor, metus nunc tristique sem, sit amet pulvinar nisi ex sed augue. Phasellus efficitur commodo viverra. Aenean tortor tortor, imperdiet id diam a, posuere tristique arcu. Nullam in arcu vitae ex suscipit lobortis eget dignissim ante. Praesent quis tincidunt lectus. Suspendisse id tortor leo. Nunc imperdiet a massa pretium porta. Sed egestas accumsan mi sit amet gravida.

Vivamus eget scelerisque turpis, non convallis dui. Nam nec nulla orci. Suspendisse mauris dui, aliquet vel sapien vitae, posuere commodo lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quam est, gravida eu neque ac, rutrum cursus leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec euismod massa eu nibh vulputate hendrerit. Donec eu nibh quis nibh porttitor rhoncus sit amet et nisl. Aliquam finibus urna ut neque congue, vel congue nunc commodo. Duis eget metus eu felis tempor laoreet id id ante. Integer nec nisl fringilla, lacinia nunc et, imperdiet odio. Vivamus hendrerit tristique varius. Integer diam purus, facilisis et quam ac, consequat facilisis sapien. In sed egestas dui. Mauris hendrerit tellus quam, at laoreet erat iaculis ut.

Duis auctor ex eu ultricies gravida. Vivamus pulvinar sagittis tincidunt. In at molestie ipsum, porttitor auctor mauris. In semper metus metus. Nullam luctus libero eu nisl fermentum dapibus nec in diam. Fusce rhoncus, felis eget scelerisque blandit, felis quam tempor nunc, in facilisis est velit id magna. Sed velit magna, consequat et nisl non, rutrum malesuada erat. Ut consequat mi fringilla suscipit sodales. Duis convallis elit risus, at rhoncus diam luctus sagittis. Aenean vestibulum condimentum purus, quis finibus ipsum egestas et. Nunc venenatis, lectus non imperdiet commodo, leo odio cursus ex, quis pulvinar ante purus placerat risus. Vestibulum rhoncus tristique aliquam. Maecenas placerat, nisl vitae rutrum consequat, urna eros commodo elit, sit amet pharetra mauris est quis tellus. Nulla semper arcu eget dictum semper. Suspendisse interdum augue ac lorem facilisis sollicitudin. Cras tortor augue, hendrerit nec facilisis vel, dignissim vel mauris.

Donec ut leo finibus justo iaculis facilisis non vel dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam molestie velit sagittis gravida dapibus. Nunc placerat, mauris quis iaculis vulputate, metus diam tristique nisi, non commodo metus leo quis ex. Etiam enim ligula, pretium a tempor et, elementum id lorem. Donec mollis porttitor fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam cursus lorem eget facilisis imperdiet. In pretium dui quis tempus cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris euismod auctor sagittis. Nam eu iaculis enim. Aliquam tempus efficitur tempor. Proin egestas viverra risus id pharetra. Duis pretium congue neque, a feugiat nibh malesuada ac. Integer vitae dapibus lacus.

Vestibulum a vulputate enim, id placerat tellus. Etiam sit amet nisi nec felis aliquam sodales vehicula sed purus. Donec ultricies consectetur eleifend. Aliquam imperdiet nisl euismod faucibus ornare. Mauris non sem tincidunt, bibendum ligula sed, fermentum leo. Duis mollis, leo ut maximus blandit, arcu nisi dignissim felis, a condimentum libero leo in ex. Curabitur viverra justo nec est bibendum vestibulum vitae accumsan massa. Nunc interdum mollis libero et fermentum. Phasellus ac tellus efficitur, congue nisl at, efficitur odio. Duis fermentum ex orci, a hendrerit eros placerat in. Nullam luctus tempus consectetur. Donec et facilisis dolor. Nam orci turpis, suscipit vitae porta id, rutrum sed libero. Donec elit orci, egestas nec ligula quis, consectetur faucibus nisl. Quisque ullamcorper a justo rutrum egestas.

Fusce tincidunt ex lacus, nec laoreet lacus cursus vitae. Ut laoreet eleifend ante, posuere luctus nisl. Sed vitae mattis urna. Phasellus in gravida nulla. Nullam placerat, mauris non mollis fermentum, dui dolor lacinia sem, non viverra dolor diam in lorem. Duis dictum nibh gravida, consequat sem in, imperdiet lorem. Praesent a interdum mi.

Nulla facilisi. Donec ultrices gravida elit eu porta. Curabitur suscipit nunc quis convallis faucibus. Maecenas id lectus purus. Phasellus purus augue, eleifend ut ex et, aliquet porta erat. Nulla rutrum vestibulum diam at fermentum. Nulla ultricies massa sit amet sapien commodo scelerisque.

Aliquam posuere aliquam lorem in fringilla. Praesent tincidunt leo odio, vitae pulvinar nibh pellentesque a. Morbi id tortor eu ligula porttitor convallis. Cras tristique risus ac ipsum scelerisque viverra. Ut pulvinar, dui ut malesuada suscipit, purus eros euismod magna, nec ultrices sem ligula ac nisi. Etiam laoreet luctus sem, quis rhoncus velit malesuada sed. Aliquam sit amet nulla felis. Ut vitae diam sit amet est ultricies ornare eu quis ante. Aliquam dignissim consequat nunc sed convallis. Suspendisse potenti. Praesent eu semper ante. Etiam est arcu, lobortis ut sapien nec, commodo aliquet felis. Suspendisse ut gravida sapien, in semper felis.

Vestibulum sollicitudin vel ex non euismod. Phasellus eleifend ullamcorper ligula, vel euismod est vestibulum sit amet. Phasellus tristique libero sed felis egestas, ut posuere sem tempus. Nunc diam leo, porta nec tortor sed, iaculis consequat dui. Aliquam varius felis id enim semper, a laoreet nisi lobortis. Maecenas tincidunt, felis eget vehicula lobortis, sem felis fringilla ante, ut mollis ligula lorem eu lectus. Cras sed nulla et arcu scelerisque finibus id id erat. Praesent porta, orci quis eleifend malesuada, justo libero consequat massa, ut faucibus justo nisi at velit. Pellentesque maximus bibendum mi, quis pellentesque justo vestibulum ac. Vestibulum interdum, neque ac pharetra maximus, felis purus aliquet orci, et porttitor odio elit tempus felis. Proin neque ante, pulvinar in turpis a, pellentesque maximus ex. Praesent tempus sapien sed diam faucibus semper.

Vestibulum molestie mattis dui, non iaculis felis dictum vitae. Praesent commodo at quam efficitur semper. Maecenas tincidunt quam non est vestibulum porta. Pellentesque malesuada magna ac feugiat maximus. Fusce eget neque id mi sodales convallis ac non felis. Ut euismod lacinia pharetra. Nam imperdiet, eros eu blandit ornare, eros est hendrerit metus, sit amet porttitor tellus lectus vitae purus. Curabitur leo ex, gravida nec mi vitae, tincidunt suscipit est. Nunc ut pellentesque diam. Mauris efficitur, massa non hendrerit bibendum, magna turpis ultricies ex, at viverra dui nibh ac dui.

Vivamus interdum ante vitae odio ornare ultricies. Curabitur dolor nisl, convallis non orci blandit, congue pulvinar lectus. Sed viverra congue urna eget suscipit. Aenean feugiat justo magna, ut varius quam gravida ut. Quisque maximus tincidunt lectus ac auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc condimentum sem sed bibendum ullamcorper. Vivamus purus metus, faucibus et scelerisque tempus, dictum id erat. Aliquam sollicitudin eget leo sit amet consequat. Ut sodales arcu non tellus maximus, a vestibulum quam dignissim. Vestibulum nisl nulla, sollicitudin et congue et, consectetur id eros. Pellentesque non tortor eget augue fringilla tempor. Integer id euismod turpis, quis sodales risus. Pellentesque pellentesque erat urna, id consequat turpis tristique at. Aenean a dui est. Nam laoreet lorem at feugiat blandit.

Quisque ut finibus est. Sed vitae commodo ligula. Proin at nisl sed augue tincidunt accumsan ac vel ipsum. Donec pulvinar purus sed lobortis accumsan. Nunc sit amet iaculis lacus. Sed porttitor elementum justo in viverra. Aenean facilisis molestie ligula, eu iaculis velit bibendum vel. Vestibulum eu lectus semper, luctus dui a, elementum sapien. In at sollicitudin ligula. Sed massa mauris, pellentesque eu rhoncus vel, sollicitudin vel urna.

Nulla tortor ipsum, mattis ac elit in, efficitur consequat libero. Cras sit amet magna consectetur purus dictum tempor ac eu ante. Sed blandit lacus eget ante fringilla, et vulputate eros condimentum. Cras non lectus a velit tristique venenatis semper eget nisi. Morbi blandit massa quis suscipit gravida. Sed laoreet sagittis viverra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc odio nulla, pharetra a dapibus vel, sollicitudin sed erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque placerat sit amet mi vel semper. Sed rutrum pellentesque ex non dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean et lacinia justo, id maximus ante.

Praesent eu rhoncus lorem, non sodales mauris. Sed accumsan, nisi ac consequat vehicula, arcu odio venenatis metus, eu facilisis nulla ex et justo. Vivamus at risus id libero lacinia congue sed a dui. Integer eu nunc nec magna sagittis faucibus. Ut elit nibh, porta vel augue eget, aliquam aliquet sapien. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tempor lectus nec aliquet congue. Fusce ultrices, ante at malesuada fringilla, enim turpis maximus tortor, in condimentum arcu tellus sit amet sapien. Quisque feugiat cursus libero.

Donec eget mauris in nisi elementum tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur euismod vulputate dui quis porta. Nam sodales, justo ac commodo mattis, tellus tortor consequat justo, vel eleifend tellus diam eu est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur vel mi non neque venenatis faucibus. Etiam quis placerat lacus. Vestibulum vitae ante ligula.

Vivamus ultricies sapien a lacus bibendum, porttitor pretium purus congue. Praesent lacinia commodo erat eu malesuada. Maecenas id ligula ligula. Praesent sed nisl in lorem sodales fermentum. Proin pretium ipsum non luctus cursus. Fusce ac neque id sem lacinia semper. Ut euismod felis orci. Ut elementum lectus nec diam elementum pretium. Sed vel rhoncus diam. Proin eget libero in lacus eleifend maximus sed id massa.

Cras at dui nec orci bibendum tempor vitae et est. Praesent tincidunt ex vel porttitor sollicitudin. Proin tellus lacus, gravida sed vulputate non, dapibus vitae ante. In ac tincidunt dui, sed fermentum lectus. Sed at malesuada eros. Ut commodo vulputate varius. Curabitur ornare ligula sit amet volutpat accumsan. Ut mi lorem, vestibulum sit amet porta convallis, imperdiet dapibus nisi. Duis non semper lectus. Nullam venenatis hendrerit nisl in congue. Cras suscipit laoreet turpis, ac dapibus nunc rutrum vel. Fusce malesuada odio et euismod accumsan.

Sed tincidunt viverra nunc ac consectetur. Sed ut erat augue. Etiam sed ultricies mi, sed pulvinar ipsum. Vivamus finibus mauris eu justo tincidunt feugiat. Proin a felis ut mi malesuada elementum sed sollicitudin lacus. Morbi odio dolor, posuere eu sodales et, imperdiet at nisi. Suspendisse tincidunt ligula at lacinia lacinia.

Nunc sed ligula libero. Curabitur vel vestibulum quam. Praesent lobortis urna ac posuere pellentesque. Morbi sollicitudin enim nisl, in eleifend justo posuere et. Cras a vestibulum tortor. Nulla feugiat fringilla urna varius maximus. Duis finibus augue et placerat volutpat. Duis malesuada rutrum felis, ac porttitor lorem. Phasellus rutrum vulputate mattis. Suspendisse ac tortor id lorem condimentum hendrerit ut id massa. Mauris mi arcu, dictum id pretium quis, pulvinar nec elit. Integer tincidunt arcu vitae leo venenatis, placerat iaculis nisi fermentum. Suspendisse scelerisque quis enim in auctor.";
    }
}
